# using docker-compose ==> easier to manage
version: '3.4'

services:
  web:
    image: social-media-app
    build: .
    command: "node index.js"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"